services:
  postgres:
    image: postgres:16-alpine
    container_name: xmlparser-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: xmlparser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
